[package]
name = "dhcp"
version = "0.1.0"
authors = ["Palkovsky <dawidmacek42@gmail.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.9.0"
arrayref = "0.3.5"
phf = { version = "0.8.0", features = ["macros"] }